In [1]:
import pandas as pd
import numpy as np

In [105]:
outlier_activities = pd.read_csv("../../160-Stackoverflow-Data/residuals/data/outlier_activities.csv")
outlier_question = pd.read_csv("../../160-Stackoverflow-Data/residuals/data/outlier_question.csv")

In [103]:
outlier_question

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Id,ParentId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,OwnerDisplayName,LastEditorUserId,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate
0,2,2,67737,11209935,NaN,NaN,2012-06-26T14:46:59.163,2,10504.0,<p>I 'm getting the date in the following form...,964819.0,NaN,904049.0,Changing one date format to another,java date format,4.0,1,NaN,NaN
1,13,13,1296,8741054,NaN,8741143.0,2012-01-05T10:37:18.253,0,1732.0,<p>How to resolve warning message coming in ec...,374199.0,NaN,1977903.0,Eclipse Warning message,java eclipse,5.0,6,0.0,NaN
2,14,14,43834,10314404,NaN,10314451.0,2012-04-25T11:09:04.190,-2,2842.0,<p>I am working on Galaxy Nexus(Android 4.0.3)...,896579.0,NaN,136445.0,How to save captured image to gallery,java android emulation samsung-mobile,2.0,1,NaN,NaN
3,23,23,68460,11239086,NaN,11239128.0,2012-06-28T06:23:16.197,132,291504.0,<blockquote>\r\r\r\n <p><strong>Possible Dupl...,1439243.0,NaN,-1.0,java.lang.UnsupportedClassVersionError Unsuppo...,java,7.0,0,33.0,2013-02-04T07:29:18.850
4,24,24,20678,9484820,NaN,NaN,2012-02-28T15:33:14.167,-1,1488.0,<p>I have an html file called basic.html and w...,1178770.0,NaN,1400768.0,Regex - find various strings from an HTML file,java html regex,2.0,4,NaN,2014-09-27T14:44:12.220
5,25,25,7965,8998383,NaN,8998417.0,2012-01-25T05:44:44.303,3,516.0,<p>I use a <code>PriorityBlockingQueue</code> ...,976646.0,NaN,230513.0,Re ordering of a priorityblockingqueue after a...,java queue,1.0,0,1.0,NaN
6,32,32,41094,10216014,NaN,10221981.0,2012-04-18T18:53:39.423,21,32389.0,<p>My application must perform R operations su...,1340020.0,NaN,59087.0,Simple program to call R from Java using Eclip...,java eclipse r rserve,4.0,0,13.0,NaN
7,35,35,2852,8799282,NaN,8803011.0,2012-01-10T06:13:30.450,-1,2484.0,"<p>with vmware web service SDK and Axis 1.4, E...",677823.0,NaN,1965870.0,java program for managing the ESXi with web se...,java vmware esxi,2.0,0,NaN,NaN
8,36,36,8479,9018589,NaN,9018678.0,2012-01-26T13:15:02.987,0,1208.0,<p>I have 2 classes <code>Engine.java</code> a...,1092450.0,NaN,714968.0,Accessing Swing components of another class wi...,java swing methods components parent,4.0,1,NaN,NaN
9,42,42,64944,11098013,NaN,11098831.0,2012-06-19T09:20:09.203,8,19289.0,<p>I have issue with:</p>\r\r\r\n\r\r\r\n<pre>...,213158.0,NaN,1061499.0,spring <form:checkboxes> tag and css class,java jsp,3.0,2,4.0,NaN
10,50,50,36688,10062096,NaN,10062147.0,2012-04-08T10:27:39.087,0,441.0,<p>Started learning Wicket after ASP.NET MVC a...,852604.0,NaN,611274.0,Wicket human-readable URLs,java html url wicket,2.0,0,1.0,NaN
11,58,58,19154,9428573,NaN,9431863.0,2012-02-24T09:45:51.050,40,21835.0,<p>I'm running a web application on Tomcat. I ...,419889.0,NaN,157882.0,Is it safe to use a static java.sql.Connection...,java multithreading servlets jdbc connection,2.0,0,28.0,NaN
12,59,59,59949,10906456,NaN,10906480.0,2012-06-05T23:40:11.413,0,1308.0,<p>The section of code in question is:</p>\r\r...,1245581.0,NaN,NaN,"JavaCompiler giving NullPointerException on ""T...",nullpointerexception java,3.0,1,NaN,NaN
13,61,61,14171,9243389,NaN,NaN,2012-02-11T19:33:10.227,0,294.0,<p>Is there any way to find out whether a new ...,713328.0,NaN,NaN,Sql server 2005 knowing new record is inserted,java tsql,4.0,1,NaN,NaN
14,63,63,29039,9787045,NaN,9787098.0,2012-03-20T12:47:50.483,2,1040.0,<p>Is there a way to set <code>ResetSeqNumFlag...,249571.0,NaN,243373.0,Quickfix setting ResetSeqNumFlag,java quickfix quickfixj,2.0,0,NaN,NaN
15,66,66,56325,10770327,NaN,10770345.0,2012-05-26T22:42:28.657,0,342.0,<p>I'm making an Android app and my implementa...,1419374.0,NaN,382471.0,Why does adapter.add() create an infinite loop...,java android loops adapter,1.0,0,NaN,NaN
16,68,68,66923,11176857,NaN,NaN,2012-06-24T10:57:20.983,0,51.0,<p>I have gone thru the egit tutorial doc here...,835083.0,NaN,NaN,Always using remote repository in egit,java eclipse github egit,2.0,0,NaN,NaN
17,72,72,58323,10842843,NaN,NaN,2012-06-01T00:06:07.007,0,965.0,<p>Ok... in my quest for surfing the web progr...,1419358.0,NaN,397016.0,apache http client,java android facebook apache,2.0,0,0.0,NaN
18,73,73,66660,11166717,NaN,NaN,2012-06-23T03:56:37.893,3,1012.0,<p>Suppose I insert ten rows to a table using ...,155684.0,NaN,1065180.0,Spring SimpleJDBCInsert - How to get generated...,java spring jdbc,0.0,2,3.0,NaN
19,79,79,28559,9769147,NaN,9769207.0,2012-03-19T11:14:29.137,0,1343.0,<p>I am looking for establishing communication...,816868.0,NaN,1039361.0,Voice communication between two android's over...,java android sockets wifi,2.0,1,3.0,NaN
20,82,82,24015,9608674,NaN,9608722.0,2012-03-07T20:37:53.750,3,956.0,<pre><code>class A{\r\r\r\n A aob;\r\r\r\n...,953263.0,NaN,953263.0,How many objects eligible for Garbage Collector,java scjp ocpjp,3.0,1,2.0,NaN
21,83,83,1168,8735684,NaN,NaN,2012-01-04T23:38:24.647,2,2991.0,<p>I am looking at options for adding a releva...,114874.0,NaN,NaN,What is a good server-side RSS feed aggregator...,java rss,2.0,0,2.0,2013-02-25T08:40:22.417
22,85,85,52151,10615618,NaN,NaN,2012-05-16T09:26:41.853,0,2239.0,<p>I want to exploit the db independent HQL an...,927326.0,NaN,NaN,How to use Hibernate Criteria API without Enti...,java hibernate,3.0,4,NaN,NaN
23,89,89,334,8703229,NaN,NaN,2012-01-02T16:43:35.010,0,392.0,<p>I'm trying to establish Bluetooth communica...,259288.0,NaN,NaN,bluetooth serial port not visible,java bluetooth,1.0,0,NaN,NaN
24,96,96,34018,9966196,NaN,9966805.0,2012-04-01T16:44:55.833,0,1900.0,"<p>I have about 500 cd's that need backing up,...",462604.0,NaN,462604.0,Ripping an audio CD in Python/Java,java python audio ripping,4.0,10,1.0,NaN
25,102,102,40845,10206843,NaN,NaN,2012-04-18T09:44:57.723,5,2049.0,<p>We are currently facing the problem that so...,109430.0,NaN,109430.0,How to read and understand a monster exception...,java spring exception grails,4.0,0,1.0,NaN
26,104,104,13950,9234603,NaN,9234740.0,2012-02-10T20:47:20.063,1,3509.0,<p>I'm a SWT newbie and am having some trouble...,190758.0,NaN,NaN,SWT: veritcal separator too tall; horizontal t...,java swt,2.0,0,NaN,NaN
27,106,106,20513,9478769,NaN,10200819.0,2012-02-28T08:42:49.597,7,2593.0,<p>Currently I am working on the implementatio...,576758.0,NaN,576758.0,Browser Authentication via HttpURLConnection,java http authentication,1.0,0,2.0,NaN
28,108,108,45516,10374269,NaN,NaN,2012-04-29T17:29:00.253,0,679.0,<p>I am designing an app that uses google maps...,1364432.0,NaN,643742.0,unable to use com.google.android.maps in the x...,java android xml eclipse maps,2.0,1,NaN,NaN
29,111,111,33527,9950102,NaN,9951322.0,2012-03-30T20:36:14.417,7,205.0,"<p>In following code the issue is, that I cann...",314073.0,NaN,NaN,"How to test ""add"" in DAO without using ""find"" ...",java,4.0,3,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,681,681,66836,11173518,NaN,NaN,2012-06-23T22:35:12.337,-1,147.0,<p>I am trying to test a multithreader scenari...,835083.0,NaN,835083.0,Controlling the order of execution of threads,java multithreading concurrency,3.0,5,NaN,NaN
190,685,685,11075,9120964,NaN,NaN,2012-02-02T22:27:21.003,3,1129.0,<p>I want to remove any tags such as</p>\r\r\r...,925899.0,NaN,925899.0,Java Regex or XML parser?,java regex,4.0,0,NaN,NaN
191,689,689,52923,10643451,NaN,10654463.0,2012-05-17T21:00:59.007,2,2465.0,"<p>I have a java program, which will run on wi...",1190934.0,NaN,NaN,How to determine if java program is running as...,java windows admin administration,1.0,3,NaN,NaN
192,691,691,59120,10873487,NaN,NaN,2012-06-03T19:57:47.917,0,187.0,<p>The question is:</p>\r\r\r\n\r\r\r\n<p>We h...,1433826.0,NaN,56338.0,Issue with one of the interview ques,java algorithm,2.0,0,NaN,NaN
193,694,694,52025,10610818,NaN,NaN,2012-05-16T01:14:08.193,0,445.0,<p>We are working on a new secured project.\r\...,967710.0,NaN,690854.0,PKI - card reader replacement,java ssl pki,2.0,1,1.0,NaN
194,696,696,45241,10365473,NaN,NaN,2012-04-28T16:37:58.487,0,48.0,<blockquote>\r\r\r\n <p><strong>Possible Dupl...,359862.0,NaN,-1.0,Java: How much memory is taken by an object? H...,java,0.0,6,0.0,2012-04-28T16:50:58.880
195,698,698,33067,9933082,NaN,20087226.0,2012-03-29T20:34:10.467,2,757.0,"<p>There are <a href=""http://docs.oracle.com/j...",696632.0,NaN,NaN,Correct Kerberos principal type for a hostbase...,java kerberos principal gssapi jgss,2.0,0,NaN,NaN
196,703,703,30214,9829729,NaN,9831857.0,2012-03-22T20:08:48.067,3,1256.0,<p>I'm having a problem de-compressing a ZIP f...,1283529.0,NaN,1466970.0,De-compressing a ZIP file using Java ZipFile c...,java compression zip decompression,2.0,2,NaN,NaN
197,707,707,15591,9293474,NaN,9293523.0,2012-02-15T12:33:59.187,19,7924.0,<pre><code>import java.util.HashMap;\r\r\r\nim...,1072878.0,NaN,NaN,Collection.toArray() java.lang.ClassCastException,java collections,4.0,1,5.0,NaN
198,708,708,4785,8875707,NaN,8875923.0,2012-01-16T04:16:17.600,1,572.0,<p>I have some java classes that work fine unt...,1151203.0,NaN,1151203.0,When putting my classes in a package the code ...,java,3.0,11,NaN,NaN
199,710,710,35595,10023331,NaN,10060550.0,2012-04-05T05:56:02.553,3,1961.0,<p>I'm trying to make a Java app (stand alone ...,635129.0,NaN,504958.0,Google calendar API OAUTH,java,2.0,1,1.0,NaN
200,714,714,42280,10259738,NaN,10259772.0,2012-04-21T14:23:32.880,91,199255.0,<p>How can one restart and start Tomcat 6 on ...,998983.0,NaN,1266242.0,How to restart tomcat 6 in ubuntu,java tomcat ubuntu,1.0,1,18.0,2012-12-21T16:37:25.880
201,719,719,44702,10344772,NaN,NaN,2012-04-27T04:35:39.827,0,2150.0,<p>I am working on this and getting this error...,1129764.0,NaN,NaN,Error in : java.io.InvalidClassException,java exception hash iostream,2.0,0,1.0,NaN
202,722,722,10405,9095748,NaN,9095858.0,2012-02-01T12:24:14.017,15,12402.0,<p>I was trying to understand the memory struc...,830753.0,NaN,1064325.0,Method Area and PermGen,java jvm permgen,4.0,1,5.0,NaN
203,727,727,63702,11050539,NaN,11050613.0,2012-06-15T12:20:53.660,4,16778.0,<p>I was going through an interview question i...,784597.0,NaN,784597.0,Using HashMap in multithreaded environment,java multithreading,3.0,2,4.0,NaN
204,728,728,51731,10599959,NaN,10601916.0,2012-05-15T11:42:09.697,17,14591.0,<p>Since initialization of the WS client servi...,871611.0,NaN,21234.0,Is this JAX-WS client call thread safe?,java,4.0,5,4.0,NaN
205,731,731,60889,10942679,NaN,10942738.0,2012-06-08T03:21:41.840,0,290.0,<p>We have a web application that is generatin...,1207867.0,NaN,502381.0,JMS Multiple threads processing,java multithreading jms jndi,2.0,0,NaN,NaN
206,742,742,26942,9712162,NaN,9713159.0,2012-03-15T00:02:11.673,1,511.0,<p>I have a group of 3 <code>JRadioButtonMenuI...,503900.0,NaN,NaN,Coordinating two `ButtonGroup`,java swing buttongroup,2.0,2,NaN,NaN
207,747,747,31948,9893673,NaN,9893704.0,2012-03-27T16:26:01.723,0,522.0,<p>My program crashes due to a null pointer ex...,1054011.0,NaN,1054011.0,Class Declaration causes Null Pointer Exception,java calendar nullpointerexception proguard,5.0,1,NaN,NaN
208,749,749,33172,9937314,NaN,9937387.0,2012-03-30T05:12:47.303,5,15984.0,<p>I am learning basics of EJB 3.0. I have man...,1000480.0,NaN,814702.0,Initial Context property values for EJB lookup,java jboss jndi,1.0,0,2.0,NaN
209,750,750,55891,10755717,NaN,15823140.0,2012-05-25T13:58:57.430,4,5777.0,<pre><code>public void miseAJourTranscoIdCrois...,831061.0,NaN,-1.0,Insert ... value with entityManager.persist(Ob...,java hibernate jpa persistence hql,3.0,1,1.0,NaN
210,760,760,39327,10153816,NaN,19372993.0,2012-04-14T12:58:51.803,4,12963.0,<p>I am using netbeans and apache tomcat in or...,289246.0,NaN,289246.0,run web application in netbeans,java tomcat maven netbeans,3.0,2,NaN,NaN
211,771,771,49896,10532919,NaN,NaN,2012-05-10T11:20:18.537,0,204.0,<p>I have a 2D string array that contains inte...,1386905.0,NaN,267025.0,When adding elements to string array from user...,java arrays null,1.0,7,NaN,NaN
212,775,775,39563,10161408,NaN,10161455.0,2012-04-15T10:59:38.043,157,65717.0,<p>First I'll state that I'm much more familia...,1024246.0,NaN,404623.0,Java: using switch statement with enum under s...,java enums,5.0,2,14.0,NaN
213,777,777,64016,11064020,NaN,NaN,2012-06-16T13:53:23.657,5,3716.0,<p>I am trying to understand the following cod...,1422604.0,NaN,NaN,Problems with casting and short parameters in ...,java,5.0,2,NaN,NaN
214,788,788,60660,10933088,NaN,NaN,2012-06-07T13:43:08.103,-1,39.0,<p>Lets say I have an existing long lived acce...,189296.0,NaN,NaN,"After getting a new long lived access_token, w...",java,1.0,2,NaN,NaN
215,789,789,11992,9157501,NaN,NaN,2012-02-06T08:41:01.493,1,6376.0,<p>I am a new to java. I dont know much about ...,1191852.0,NaN,1289473.0,java code to download an image from server to ...,java image download,3.0,4,2.0,NaN
216,791,791,50589,10559154,NaN,NaN,2012-05-11T21:55:29.913,1,512.0,<p>How can I see the http-session count for my...,158288.0,NaN,1049128.0,Session Count on JBoss AS 7.1,java session servlets,2.0,0,0.0,NaN
217,793,793,46838,10423128,NaN,10436912.0,2012-05-02T23:30:31.963,69,89132.0,"<p>In the app I'm developing on Android, I kee...",1371243.0,NaN,3065892.0,Android Fatal Signal 11,java android crash signals,10.0,6,7.0,NaN
218,796,796,51577,10594014,NaN,10594077.0,2012-05-15T04:06:17.647,6,4291.0,<p>I need some help understanding the advantag...,430720.0,NaN,430720.0,Difference between wait-notify and CountDownLatch,java concurrency synchronization,1.0,1,4.0,NaN

In [106]:
outlier_activities.head()

   Unnamed: 0 activity  q_num   rank     score   userid
0          10   answer      2  18145  0.001007  1429832
1          48   answer     13  36285  0.000000  1291727
2          55  comment     13  11534  0.001179  1977903
3          56     edit     13  11534  0.001179  1977903
4          57   answer     14  49244  0.000000  4993880

In [107]:
users_answered = outlier_activities[outlier_activities.activity == "answer"]

In [108]:
users_answered

     Unnamed: 0 activity  q_num   rank     score   userid
0            10   answer      2  18145  0.001007  1429832
1            48   answer     13  36285  0.000000  1291727
4            57   answer     14  49244  0.000000  4993880
5           105   answer     23  56973  0.000000  1623624
6           106   answer     23  43990  0.000000  1870570
7           107   answer     23  37008  0.000253  1178448
17          165   answer     32  47060  0.000000  2230652
18          166   answer     32  12963  0.001482  1296564
19          168   answer     32  42074  0.000000  1343059
21          177   answer     35  27117  0.000000  3011423
22          178   answer     35  28847  0.000000  1140783
23          179   answer     36  27369  0.000000  1171314
24          205   answer     42  45455  0.000000  1875761
28          269   answer     59  12844  0.001446  1115406
29          276   answer     61  17611  0.000617  1193945
30          277   answer     61  17613  0.000617   733798
31          278   answer     61  17612  0.000617   462477
33          291   answer     63  36223  0.000000  1812321
36          313   answer     68  51031  0.000000  1719370
37          324   answer     72  14327  0.001354   369933
44          384   answer     85  47786  0.000000  2098900
45          402   answer     89  15859  0.000616    35049
46          418   answer     96  12286  0.001538  1004235
47          419   answer     96   9826  0.002364  1502059
48          443   answer    102  13867  0.001349  2146216
49          444   answer    102  13868  0.001349   224354
50          453   answer    104  17567  0.000615  2136929
51          460   answer    106  52515  0.000000  1265305
53          466   answer    108  10635  0.002462   552733
54          467   answer    108  12891  0.001727  1273266
..          ...      ...    ...    ...       ...      ...
329        2888   answer    675  36470  0.000000  3789431
330        2894   answer    675  54635  0.000000  5423668
331        2895   answer    675  47504  0.000000  6574704
334        2920   answer    681  12128  0.001730  1470868
335        2941   answer    685  32937  0.000000  1565758
337        2960   answer    691  13458  0.001467  1407156
340        2992   answer    698  35280  0.000000  2594812
343        3035   answer    708  36518  0.000000  8500062
344        3050   answer    710  12484  0.001344  1073550
352        3095   answer    722  44380  0.000000  4071413
353        3097   answer    722  51475  0.000000  2046862
357        3126   answer    728  42660  0.000000  1469259
358        3128   answer    728  40393  0.000000  7964197
359        3143   answer    731  46350  0.000000  1479668
360        3182   answer    742  53349  0.000000  1520126
361        3197   answer    747  52620  0.000000  1657131
363        3213   answer    750  47441  0.000000  1452289
365        3253   answer    760  36173  0.000000  2881090
367        3314   answer    775  20688  0.000617   842607
371        3369   answer    789  29663  0.000000  3497603
372        3370   answer    789  27812  0.000000  1533909
374        3382   answer    791  42510  0.000000  4222206
376        3388   answer    793  54572  0.000000  1656663
377        3390   answer    793  13311  0.001441   449918
378        3391   answer    793  13312  0.001441  1323666
379        3392   answer    793  53815  0.000000  1392727
380        3393   answer    793  51651  0.000000  1644096
381        3395   answer    793  52408  0.000000  3481068
382        3396   answer    793  35478  0.000000  2086234
383        3397   answer    793  13313  0.001441   860351

[219 rows x 6 columns]

In [110]:
grouped = users_answered.groupby(users_answered.userid)
num_missed_user = grouped.size()
print(num_missed_user[num_missed_user > 1]) # almost all the users above the threshold only detected once
print(len(num_missed_user)) # 212, the number of users who did answer but we couldn't detect them

userid
4669617    2
dtype: int64
218

In [64]:
Users = pd.read_csv("../../160-Stackoverflow-Data/train_test/raw_query/Users.csv")

In [65]:
Users.tail()

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,Age,AboutMe,Views,UpVotes,DownVotes,AccountId,ProfileImageUrl
59191,9421723,11,2018-02-28T02:15:12.180,idontknowwhatiamtalkingabout,2018-03-10T20:20:57.933,NaN,NaN,NaN,NaN,1,0,0,13037259,NaN
59192,9427004,1,2018-03-01T04:22:08.210,user9427004,2018-03-10T18:35:10.737,NaN,NaN,NaN,NaN,0,0,0,13044838,NaN
59193,9446684,1,2018-03-05T15:56:36.757,debanga medhi,2018-03-08T16:30:24.563,NaN,NaN,NaN,NaN,0,0,0,13073918,NaN
59194,9463264,11,2018-03-08T16:15:18.027,Mrseguin,2018-03-09T16:56:14.843,NaN,NaN,NaN,NaN,0,0,0,13097900,NaN
59195,9464197,1,2018-03-08T19:49:11.937,Sujal Shelke,2018-03-09T20:51:23.280,NaN,NaN,NaN,NaN,0,0,0,13099281,https://lh5.googleusercontent.com/-S6_B7QefsRM...

In [48]:
Posts = pd.read_csv('../../160-Stackoverflow-Data/train_test/raw_query/Posts.csv' ,\
                    dtype = {'LastEditorDisplayName': str, 'Tags': str})

C:\Users\seungmi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (16,21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [49]:
Answers = Posts[Posts.PostTypeId == 2]

In [50]:
Answers.head()

,Unnamed: 0,Id,PostTypeId,ParentId,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,CommunityOwnedDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate
69312,69312,8691334,2,8691270.0,NaN,2012-01-01T01:00:17.023,4,NaN,"<p>If your goal is to center a component, then...",535871.0,...,NaN,2012-01-01T01:19:12.777,2012-01-01T01:19:12.777,NaN,NaN,NaN,NaN,2,NaN,NaN
69313,69313,8691341,2,8691225.0,NaN,2012-01-01T01:03:04.670,1,NaN,<ol>\r\r\n<li><p>Check the software firewall o...,139985.0,...,NaN,NaN,2012-01-01T01:03:04.670,NaN,NaN,NaN,NaN,1,NaN,NaN
69314,69314,8691449,2,8691436.0,NaN,2012-01-01T01:41:31.107,2,NaN,<p>The traditional <code>for</code> loop versi...,535871.0,...,NaN,NaN,2012-01-01T01:41:31.107,NaN,NaN,NaN,NaN,0,NaN,NaN
69315,69315,8691450,2,8691436.0,NaN,2012-01-01T01:42:03.593,2,NaN,<p>You are going to want to use the following....,974000.0,...,NaN,NaN,2012-01-01T01:42:03.593,NaN,NaN,NaN,NaN,0,NaN,NaN
69316,69316,8691503,2,8691456.0,NaN,2012-01-01T02:07:39.687,2,NaN,<p>Don't use the <code>UrlEncodedFormEntity</c...,751158.0,...,NaN,NaN,2012-01-01T02:07:39.687,NaN,NaN,NaN,NaN,3,NaN,NaN

In [51]:
num_answers_user = Answers.groupby(Answers['OwnerUserId']).size()

In [111]:
# build a dataframe that indicates the number of missed answers and total answers of users that we couldn't detect at least one answer
missed_user_table = pd.merge(num_missed_user.to_frame(), num_answers_user.to_frame(), left_index = True, right_index = True)  
missed_user_table.columns = ['missed', 'total']

In [112]:
missed_user_table

           missed  total
5746.0          1      1
14204.0         1      1
15806.0         1      1
20520.0         1      2
35049.0         1      1
35989.0         1      1
113794.0        1      1
136913.0        1      3
151770.0        1      1
190652.0        1      1
204213.0        1      1
224354.0        1      1
225833.0        1      1
236081.0        1      1
241658.0        1      1
252871.0        1      1
289723.0        1      1
296526.0        1      1
336423.0        1      5
350421.0        1      1
362581.0        1      1
369933.0        1      1
377366.0        1      1
386110.0        1      1
400251.0        1      2
403950.0        1      2
410414.0        1      2
430952.0        1      1
449918.0        1      1
462477.0        1      1
...           ...    ...
4315585.0       1      1
4369141.0       1      2
4515438.0       1      1
4574869.0       1      1
4669617.0       2      4
4830754.0       1      1
4993880.0       1      1
5109863.0       1      1
5148088.0       1      1
5177498.0       1      1
5199515.0       1      1
5221960.0       1      1
5263786.0       1      1
5310843.0       1      1
5374897.0       1      1
5423668.0       1      1
5703813.0       1      1
5703847.0       1      1
5791058.0       1      1
6004969.0       1      1
6345090.0       1      1
6574704.0       1      2
6649442.0       1      1
6675805.0       1      1
7197188.0       1      1
7540151.0       1      1
7906919.0       1      1
7964197.0       1      1
8500062.0       1      1
9082413.0       1      1

[218 rows x 2 columns]

In [115]:
len(missed_user_table[missed_user_table.total == missed_user_table.missed]) 
# 159 users of 212 who did answer only once and we couldn't detect them
# 53 users of 212 who did answer more than twice

159

In [116]:
# focus on those 159 users first
single_ans = (missed_user_table[missed_user_table.total == missed_user_table.missed]).index # user_id

In [117]:
single_ans_users = Users[Users['Id'].isin(single_ans)]

In [118]:
single_ans_users.sort_values(['Views'])

,Id,Reputation,CreationDate,DisplayName,LastAccessDate,WebsiteUrl,Location,Age,AboutMe,Views,UpVotes,DownVotes,AccountId,ProfileImageUrl
59160,9082413,1,2017-12-11T07:00:22.160,Ambikesh Kumar Shukla,2018-03-09T10:57:37.037,NaN,"Pune, Maharashtra, India",NaN,NaN,0,0,0,12476106,https://lh5.googleusercontent.com/-whhbc340c3A...
57454,5199515,1,2015-08-06T19:03:24.343,James,2018-03-08T10:54:03.173,NaN,Switzerland,NaN,<p>passionate software engineer and beer brewe...,0,0,0,6748763,NaN
52387,2211634,1,2013-03-26T12:52:51.683,Neumi,2013-09-11T14:04:36.253,NaN,NaN,NaN,NaN,0,0,0,2547036,NaN
58442,6675805,1,2016-08-04T01:53:21.403,jayr kray,2016-08-22T02:09:45.523,NaN,NaN,NaN,NaN,0,0,0,8949231,NaN
52582,2275761,11,2013-04-12T19:18:20.097,Mike,2013-07-19T09:59:40.637,NaN,NaN,NaN,NaN,0,0,0,2629412,NaN
50458,1710007,21,2012-09-30T15:58:47.170,Ambrose,2012-10-10T19:01:57.293,NaN,NaN,NaN,NaN,0,0,0,1892233,NaN
58898,7906919,11,2017-04-22T19:09:53.013,Ray,2017-04-22T19:09:53.013,NaN,NaN,NaN,NaN,0,0,0,10745417,NaN
58645,7197188,11,2016-11-22T23:11:09.700,user7197188,2016-11-24T16:08:54.330,NaN,NaN,NaN,NaN,0,0,0,9702768,NaN
52061,2112037,24,2013-02-26T16:17:08.090,Harun,2014-06-26T14:48:46.860,NaN,NaN,NaN,NaN,1,0,0,2418479,NaN
57404,5148088,11,2015-07-23T12:35:21.523,LoloDuSud,2015-08-06T15:53:45.520,NaN,NaN,NaN,NaN,1,0,0,6672309,NaN
57939,5791058,21,2016-01-14T17:30:45.573,Slava84,2017-05-03T13:56:37.707,NaN,NaN,NaN,NaN,1,0,0,7638089,https://www.gravatar.com/avatar/30899d17403818...
52721,2323008,131,2013-04-26T08:44:26.017,user67871,2018-03-09T12:25:00.503,NaN,NaN,NaN,NaN,1,0,0,1536283,NaN
53576,2625326,1,2013-07-27T09:46:51.660,sascha.arthur,2015-07-30T14:57:53.210,NaN,NaN,NaN,NaN,1,0,0,3101266,NaN
57503,5263786,1,2015-08-25T10:13:16.837,David Dominguez,2016-07-28T15:07:15.447,NaN,NaN,NaN,NaN,1,0,0,6844577,https://lh5.googleusercontent.com/-TpGGz2osqEw...
57356,5109863,1,2015-07-13T06:44:31.180,Sriram,2018-02-20T13:31:07.177,NaN,NaN,37.0,NaN,1,0,0,6616970,https://www.gravatar.com/avatar/3704b2e375f8ff...
55819,3789431,1,2014-06-30T07:48:46.220,Atikant Negi,2014-06-30T07:48:46.220,NaN,NaN,NaN,NaN,2,0,0,4680627,NaN
57060,4830754,1,2015-04-25T02:02:48.313,sada,2015-10-14T02:48:43.763,NaN,NaN,NaN,NaN,2,0,0,6200938,NaN
46911,1432658,11,2012-06-02T16:54:35.533,Jwalant,2012-06-02T16:54:35.533,http://www.apekshit.com,NaN,NaN,NaN,2,0,0,1536866,NaN
36873,1246042,1,2012-03-02T21:46:49.563,user1246042,2013-10-03T19:44:57.870,NaN,NaN,NaN,NaN,2,0,0,1294662,NaN
58915,7964197,106,2017-05-04T15:34:22.977,Jether,2018-03-08T12:29:33.860,NaN,NaN,NaN,NaN,3,17,0,10829205,NaN
58800,7540151,41,2017-02-09T12:13:44.680,Bruno Muniz,2018-01-03T23:18:28.573,NaN,NaN,NaN,NaN,3,10,0,10068509,https://i.stack.imgur.com/RaWha.png?s=128&g=1
53314,2530822,29,2013-06-28T06:47:31.450,TotoliciCristian,2017-11-22T07:24:55.073,NaN,"Galati, Romania",27.0,<p>Always glad to improve my skills and learn ...,3,0,0,2980833,NaN
54231,2881090,36,2013-10-15T03:49:25.567,agaqeu,2017-06-19T01:05:05.500,http://agaqeu.users.sourceforge.net/,Brazil,NaN,NaN,4,0,0,3438640,https://www.gravatar.com/avatar/d66ab50ef647fc...
32351,1171314,24,2012-01-26T13:21:38.550,CAA,2012-01-26T13:21:38.550,NaN,NaN,NaN,NaN,4,0,0,1200565,NaN
55355,3481068,21,2014-03-31T12:32:33.240,David Fetcher,2015-05-22T18:15:00.317,NaN,NaN,29.0,NaN,4,0,0,4255190,https://www.gravatar.com/avatar/2e9290b38863cb...
54487,3011423,24,2013-11-20T03:15:27.427,Grv,2014-04-14T18:40:44.770,NaN,"San Jose, CA",NaN,<p>Graduate student at san jose state universi...,4,0,0,3610319,https://www.gravatar.com/avatar/?s=128&d=ident...
37148,1250684,1,2012-03-05T19:57:18.770,here comes the drop,2012-03-07T20:01:11.537,NaN,NaN,NaN,NaN,4,0,0,1300689,NaN
22879,933890,26,2011-09-08T01:43:35.440,codenoob,2015-07-08T02:07:02.547,NaN,NaN,NaN,NaN,5,0,0,896822,NaN
52627,2290912,1,2013-04-17T13:16:20.080,shailendra sharma,2016-10-24T13:28:32.720,NaN,NaN,NaN,NaN,5,0,0,2648703,NaN
51597,1987479,11,2013-01-17T14:39:54.773,Emmanuel,2013-01-29T08:32:39.507,NaN,NaN,NaN,NaN,5,0,0,2256369,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33699,1193945,5605,2012-02-07T06:04:05.320,John Dewey,2017-02-25T05:11:18.523,NaN,"Anna, TX, United States",NaN,<p>I write SQL Server ETL packages for a livin...,243,61,6,1228964,https://i.stack.imgur.com/jLp82.png
53492,2594812,3961,2013-07-18T09:19:27.280,Sam Hartman,2018-02-27T01:20:52.920,NaN,NaN,NaN,NaN,252,435,444,3062435,NaN
46785,1429832,1048,2012-06-01T03:53:11.397,Din Islam Milon,2018-03-08T19:51:45.660,NaN,"Dhaka, Dhaka Division, Bangladesh",26.0,<p>One line to describe me:<br/>\r\nPassionate...,262,120,1,1533165,https://i.stack.imgur.com/NWHAt.jpg?s=128&g=1
580,14204,3979,2008-09-16T22:31:05.703,Laplie Anderson,2018-03-09T20:23:50.383,NaN,"Miami, FL, United States",NaN,NaN,270,660,7,8035,NaN
45033,1392727,2770,2012-05-13T23:01:06.380,Vikas,2018-03-10T08:55:23.723,NaN,"Hyd, India",NaN,"<p>Pictures:\r\n<a href=""http://500px.com/chou...",281,1586,5,1484122,https://i.stack.imgur.com/YoYNr.jpg?s=128&g=1
20460,842607,2075,2011-07-13T11:49:50.450,Jimit Patel,2018-03-10T18:16:30.863,NaN,"Mumbai, India",31.0,<p>I have started my career as Android App dev...,287,347,31,448418,NaN
3679,151770,1750,2009-08-06T12:56:56.737,Roaders,2018-03-10T05:29:01.070,http://giles.roadnight.name,"London, United Kingdom",40.0,<p>Previously a Flex developer now moving into...,291,68,4,50850,NaN
8167,350421,1023,2010-05-25T23:29:40.593,jasonflaherty,2018-02-27T16:45:08.130,http://jasonflaherty.com,NorCal,NaN,<p>“Let him who is without sin cast the first ...,325,458,1,142611,NaN
20653,848393,2784,2011-07-17T05:12:26.047,The Awnry Bear,2014-06-25T13:06:18.473,http://www.awnry.com/,"Conway, AR",33.0,<p>I've been working as a professional web dev...,326,302,4,452129,NaN
46679,1427694,775,2012-05-31T06:50:43.173,lab bhattacharjee,2018-03-08T12:27:58.933,NaN,"Kolkata, India",NaN,"<ol>\r\n<li><p><a href=""http://in.linkedin.com...",345,33,1,1530368,NaN
259,5746,3726,2008-09-11T08:26:47.897,Erlend,2018-03-09T14:15:42.697,NaN,NaN,NaN,NaN,366,126,17,3921,NaN
5957,252871,5675,2010-01-18T01:26:01.437,SteelBytes,2018-03-11T03:50:06.923,http://www.SteelBytes.com,Australia,NaN,NaN,372,123,10,92247,https://i.stack.imgur.com/kyo5Y.jpg
48566,1472331,10665,2012-06-21T13:55:44.760,Luis,2018-03-09T15:23:14.313,NaN,NaN,NaN,NaN,373,88,5,1588478,NaN
53350,2544089,6185,2013-07-02T19:31:17.483,Mario Rossi,2018-03-09T04:32:49.587,NaN,"Mississauga, ON, Canada",57.0,<p>38 years experience and more than 30 progra...,394,92,51,2997947,NaN
54806,3166417,4859,2014-01-06T18:01:41.870,itzhar,2018-03-09T07:58:50.567,NaN,Israel,32.0,<p>Senior Android developer</p>\r\n,396,643,3,3817409,https://i.stack.imgur.com/RYO5k.jpg
6940,296526,4583,2010-03-18T13:08:20.023,Aphelion,2018-03-10T08:41:34.067,NaN,"Utrecht, Netherlands",32.0,NaN,412,777,44,112414,NaN
5277,224354,5041,2009-12-03T22:59:31.073,Nick Knowlson,2018-03-10T00:02:38.983,http://nickknowlson.com,Canada,30.0,"<p>Hi, I'm Nick Knowlson and two things I can'...",432,1487,9,78986,NaN
5568,236081,4352,2009-12-21T14:33:28.750,d3vid,2018-03-08T16:08:43.657,https://inkwell.za.net,"Cape Town, South Africa",38.0,NaN,432,406,27,84450,NaN
1155,35049,3286,2008-11-06T12:08:38.957,alanjmcf,2018-03-09T17:30:35.693,NaN,NaN,NaN,NaN,457,14,4,16198,NaN
8831,377366,4441,2010-06-27T11:27:40.130,KobeJohn,2018-03-10T03:01:56.620,NaN,"Kobe, Japan",NaN,NaN,457,2641,16,158604,NaN
1167,35989,7828,2008-11-09T20:27:51.163,Dipstick,2018-03-10T23:55:29.227,NaN,NaN,NaN,NaN,539,112,17,16497,NaN
51212,1886501,2230,2012-12-07T19:58:31.623,rimero,2017-08-19T14:14:34.883,http://www.rimerosolutions.com,"Toronto, ON, Canada",NaN,<p>IT Software Consultant (Java and JVM relate...,567,26,17,2123807,NaN
646,15806,1053,2008-09-17T12:54:16.220,Roshan,2017-02-15T06:31:35.547,http://roshan.info,"Zurich, Switzerland",41.0,<p>Bit Twiddler</p>\r\n,619,29,7,8705,NaN
47789,1452289,5198,2012-06-12T21:22:04.550,Hugo Dozois,2018-03-10T02:06:18.440,http://tryvoo.com,"San Francisco, CA, United States",26.0,"<p>I like solving problems, could they be in m...",772,1116,158,1562798,NaN
48463,1469259,10423,2012-06-20T12:35:17.077,CupawnTae,2018-03-10T22:34:25.517,NaN,Ireland,NaN,NaN,1005,752,29,1019629,NaN
17624,733798,13368,2011-05-02T00:49:59.047,IAmTimCorey,2018-03-11T04:47:55.953,http://www.timothycorey.com,"Clarks Summit, PA",40.0,<p>I have been a software developer and databa...,1110,1724,10,380038,NaN
5703,241658,3208,2009-12-31T17:58:08.150,Neal Gafter,2018-03-01T01:13:09.893,http://www.gafter.com/~neal,"Bellevue, WA",58.0,NaN,2048,26,6,87057,NaN
2842,113794,46531,2009-05-28T14:53:32.497,Rubens Farias,2018-03-05T17:25:42.603,http://rubensfarias.blogspot.com/,"Sao Paulo, Brazil",41.0,"<p>Software Architect, São Paulo, Brazil <br /...",2894,1597,92,39452,NaN
24371,981959,119991,2011-10-06T10:00:55.320,Jonathan Wakely,2018-03-09T02:08:45.977,http://advogato.org/person/redi/,"London, United Kingdom",NaN,"<p><img src=""https://i.imgur.com/A0xcXRD.jpg"" ...",12034,6679,1186,956801,NaN
12877,541136,123163,2010-12-13T21:54:43.753,Aaron Hall,2018-03-11T03:12:30.807,https://aaronchall.github.io/,"NYC, NY, United States",39.0,"<h3><a href=""http://meta.stackoverflow.com/q/3...",29283,2979,947,258754,https://i.stack.imgur.com/wftMn.jpg?s=128&g=1

In [95]:
sum(single_ans_users['Views'] < 100)

114

In [101]:
sum(single_ans_users['UpVotes'] == 0)

42

In [58]:
missed_user_table[missed_user_table.total != missed_user_table.missed]

           missed  total
20520.0         1      2
336423.0        1      5
400251.0        1      2
403950.0        1      2
410414.0        1      2
516188.0        1      2
525203.0        1      2
552733.0        1      2
562497.0        1      3
620249.0        1      2
877581.0        1      2
899562.0        1      2
934373.0        1      2
974935.0        1      2
1067761.0       1      3
1095795.0       1      2
1115406.0       1      3
1140783.0       1      2
1176569.0       1      2
1181921.0       1      2
1207532.0       1      3
1282835.0       1      7
1288032.0       1      9
1289716.0       1     37
1291727.0       1      2
1385039.0       1      3
1407156.0       1      3
1408036.0       1      2
1408085.0       1      5
1421402.0       1      2
1439340.0       1      3
1459214.0       1      2
1470868.0       1      3
1479668.0       1      6
1484207.0       1      3
1488406.0       1      3
1489700.0       1      4
1503163.0       1      4
1646745.0       1      3
1657131.0       1      4
1708509.0       1      2
1919879.0       1      3
2046862.0       1      3
2092205.0       1      5
2098900.0       1      2
2299789.0       1      3
2413303.0       1      2
2504224.0       1      2
2595139.0       1      2
3227495.0       1      3
4071413.0       1      2
4222206.0       1      2
4369141.0       1      2
4669617.0       2      4
6574704.0       1      2